###################################################
#---------  Alarm!NG CONFIGURATION FILE  ---------#
###################################################
##### COPY TO ~/.config/alarmng/ AND CONFIGURE TO YOUR LIKING
## Change The Audio Track
[Audio]
path = /usr/share/sounds/alarmng/Sleeping Bees.wav

## Disable/Enable/Change the Splash Screen on Startup
# Make sure to begin your custom Splash Screen with a <,> comma
# so python can understand the number of spaces required before it.
[SplashScreen]
enabled = 1
ss = ,     A        LL  Press Any    A       RRRRRRRR    MMM     MMM  II  NNN     NN  GGGGGGGGG,    A A       LL  Key To      A A      RR     RR   MM M   M MM  II  NN N    NN  GG       ,   A   A      LL  Start      A   A     RR     RR   MM  M M  MM  II  NN  N   NN  GG       ,  AAAAAAA     LL            AAAAAAA    RRRRRRR     MM   M   MM  II  NN   N  NN  GG  GGGGG, AA     AA    LL           AA     AA   RR    RRR   MM       MM      NN    N NN  GG     GG,AA       AA   LLLLLLLLLL  AA       AA  RR      RR  MM       MM  II  NN     NNN  GGGGGGGGG

#Disable/Enable The End Screen on Exit
[EndScreen]
enabled = 1
